#config_version=5
mode:
  code: mpf.modes.high_score.code.high_score.HighScore
  priority: 500
  start_events: game_ending, start_high_score
  game_mode: False
  use_wait_queue: true

high_score:
  _overwrite: True
  award_slide_display_time: 4s
  categories: !!omap
  - score:
    - HS1
    - HS2
    - HS3
    - HS4
    - HS5
    - HS6
  defaults:
    score:
      - HS1: 0
      - HS2: 0
      - HS3: 0
      - HS4: 0
      - HS5: 0
      - HS6: 0

slides:
  _overwrite: True
  high_score_enter_initials:
    - type: text
      text: "(award)"
      font_name: emulogic
      bitmap_font: True
      anchor_y: middle
      y: 24
    - type: text_input
      key: high_score
      style: dmd_small
      anchor_x: left
      anchor_y: middle
      max_chars: 5
      x: left
      y: 12
    - type: text
      text: ""
      key: high_score
      anchor_x: left
      anchor_y: middle
      x: left+4
      style: dmd_small
      y: 12

  high_score_award_display:
  - type: text
    text: (player_name)
    color: ffffff
    style: dmd_big
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle
  - type: text
    text: (award)
    color: ffffff
    style: dmd_med
    anchor_y: top
    anchor_x: middle
    y: top-1
    x: middle
  - type: text
    text: (value)
    color: ffffff
    number_grouping: true
    style: dmd_med
    anchor_y: bottom
    anchor_x: middle
    y: bottom+1
    x: middle
