#config_version=5

show_player:
  mode_attract_started:
    middleTarget:
      loops: -1
    startLED:
      loops: -1
    sideLeds:
      loops: -1
    redStuff:
      loops: -1
    jets:
      loops: -1
    dmd_show:
      loops: -1
    score_color:
      loops: -1
    cello_guy:
      loops: -1

slides:
  attractSlide:
  - type: image
    image: bg25
    fps: 30
    loops: -1

slide_player:
  mode_attract_started: attractSlide

widgets:
  fan_widget:
    - type: text
      text: FAN
      z: 3
      style: big
      color: orange
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  fan_spinner:
    - type: text
      text: FAN
      z: 3
      style: big
      color: orange
      expire: 4.5s
      animations:
        add_to_slide:
          - property: rotation
            value: -360
            duration: 4s
          - property: opacity
            value: 0
            duration: 0.5s
  tas_widget:
    - type: text
      text: TAS
      z: 3
      style: big
      color: green
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  tic_widget:
    - type: text
      text: TIC
      z: 3
      style: big
      color: magenta
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  hs1_widget:
    - type: text
      text: "(machine|score1_name)\n(machine|score1_value)"
      z: 3
      expire: 4s
  hs2_widget:
    - type: text
      text: "(machine|score2_name)\n(machine|score2_value)"
      z: 3
      expire: 2s
  hs3_widget:
    - type: text
      text: "(machine|score3_name)\n(machine|score3_value)"
      z: 3
      expire: 2s

animations:
  fade_out:
    property: opacity
    value: 0
    duration: 1.5s
    easing: in_quint


