#config_version=5

show_player:
  mode_attract_started:
    middleTarget:
      loops: -1
    startLED:
      loops: -1
    sideLeds:
      loops: -1
    redStuff:
      loops: -1
    jets:
      loops: -1
    dmd_show:
      loops: -1
  mode_attract_stopped:
    middleTarget:
      action: stop
    startLED:
      action: stop
    sideLeds:
      action: stop
    redStuff:
      action: stop
    jets:
      action: stop
    dmd_show:
      action: stop

slides:
  attractSlide:
  - type: image
    image: bg2
    fps: 30
    loops: 0
  # testSlide:
  #   - type: text
  #     text: "HS2"
  #     font_name: emulogic
  #     bitmap_font: True
  #     anchor_y: middle
  #     y: 24
  #   - type: text_input
  #     key: high_score
  #     style: dmd_small
  #     anchor_x: left
  #     anchor_y: middle
  #     max_chars: 5
  #     x: left
  #     y: 12
  #   - type: text
  #     text: "1234"
  #     key: high_score
  #     anchor_x: left
  #     anchor_y: middle
  #     x: left+4
  #     style: dmd_small
  #     y: 12

slide_player:
  mode_attract_started: attractSlide
  # mode_attract_started: testSlide

widgets:
  fan_widget:
    - type: text
      text: FAN
      z: 10
      style: dmd_big
      color: orange
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  fan_spinner:
    - type: text
      text: FAN
      z: 10
      style: dmd_big
      color: orange
      expire: 4.5s
      animations:
        add_to_slide:
          - property: rotation
            value: -360
            duration: 4s
          - property: opacity
            value: 0
            duration: 0.5s
  tas_widget:
    - type: text
      text: TAS
      z: 10
      style: dmd_big
      color: green
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  tic_widget:
    - type: text
      text: TIC
      z: 10
      style: dmd_big
      color: magenta
      expire: 1.5s
      animations:
        add_to_slide: fade_out
  hs1_widget:
    - type: text
      color: black
      text: "(machine|score1_name)\n(machine|score1_value)"
      font_name: CG-pixel
      bitmap_font: True
      z: 10
      expire: 4s
  hs2_widget:
    - type: text
      color: black
      text: "(machine|score2_name)\n(machine|score2_value)"
      font_name: CG-pixel
      bitmap_font: True
      z: 10
      expire: 2s
  hs3_widget:
    - type: text
      color: black
      text: "(machine|score3_name)\n(machine|score3_value)"
      font_name: CG-pixel
      bitmap_font: True
      z: 10
      expire: 2s

animations:
  fade_out:
    property: opacity
    value: 0
    duration: 1.5s
    easing: in_quint


