#config_version=5

show_player:
  mode_attract_started:
    middleTarget:
      loops: -1
    startLED:
      loops: -1
    sideLeds:
      loops: -1
    redStuff:
      loops: -1
    jets:
      loops: -1
    dmd_show:
      loops: -1
  mode_attract_stopped:
    middleTarget:
      action: stop
    startLED:
      action: stop
    sideLeds:
      action: stop
    redStuff:
      action: stop
    jets:
      action: stop
    dmd_show:
      action: stop

slides:
  attractSlide:
  - type: image
    image: bg2
    fps: 30
    loops: 0

slide_player:
  mode_attract_started: attractSlide

widgets:
  fan_widget:
    - type: text
      text: FAN
      z: 10
      style: dmd_big
      color: orange
      expire: 2s
      animations:
        add_to_slide: fade_out  
  fan_spinner:
    - type: text
      text: FAN
      z: 10
      style: dmd_big
      color: orange
      expire: 5.5s
      animations: 
        add_to_slide:
          - property: rotation
            value: -360
            duration: 5s
          - property: opacity
            value: 0
            duration: 0.5s
  tas_widget:
    - type: text
      text: TAS
      z: 10
      style: dmd_big
      color: green
      expire: 2s
      animations:
        add_to_slide: fade_out
  tic_widget:
    - type: text
      text: TIC
      z: 10
      style: dmd_big
      color: magenta
      expire: 2s
      animations:
        add_to_slide: fade_out
  scroll_widget:
    - type: text
      text: "for amusement only"
      font_name: emulogic
      bitmap_font: True    
      color: black
      anchor_x: left    
      x: 32
      z: 10
      expire: 6s
      animations:
        add_to_slide:
          - property: x
            value: -150
            duration: 6s
          - property: x
            value: 32
            duration: 0 s
  scroll2_widget:
    - type: text
      text: "M.\nBetz\n09/17\n----\nyeti\nfrisst\nlama\n.blog\nspot\n.com"
      font_name: CG-pixel
      bitmap_font: True
      color: black
      anchor_y: top
      y: 0
      z: 10
      expire: 7s
      animations:
        add_to_slide:
          - property: y
            value: 95
            duration: 7s
  hs1_widget:
    - type: text
      color: black
      text: "(machine|score1_name)\n(machine|score1_value)"
      font_name: CG-pixel
      bitmap_font: True
      z: 10
      expire: 5s

animations:
  fade_out:
    property: opacity
    value: 0
    duration: 2s
    # easing: in_quint


