#config_version=5

mode:
  start_events: ball_starting
  priority: 100

#-----------------------------------------------------
# Basic scoring (no special stuff, just simple hits)
# I use tags on the Switch devices to group the stuff
#-----------------------------------------------------
scoring:
  # The 4 red rollover switches at the bottom
  sw_rollover:
    score: 50
  # Waltz bonus
  sg_rollovers_default_lit_complete:
    score: 3000
  # Hit center target to light up "Ball returns" 
  # in left bottom outlane, to kick ball back onto
  # playfield and score 3000 points
  s_outlane_l_active{current_player.shot_target_mm_low_default==1}:
    score: 3000
  # Gate save scores 3000
  s_outlane_r_active{current_player.shot_gate_light_default==1}:
    score: 3000
  # When AB lanes light are ON, they score 3000
  s_lane_tl_active{current_player.shot_AB_lanes_default==1}:
    score: 3000
  s_lane_tr_active{current_player.shot_AB_lanes_default==1}:
    score: 3000

#-------------------    
# 3 stars lit = extra ball
#-------------------
# extra_balls:
#   three_stars:
#     award_events: shot_star_advance_3_hit

slides:
  scoreSlide:
    - type: text
      text: "(player1|score)"
      font_name: visitor
      color: black
      bitmap_font: True
      y: 15.0
      number_grouping: False
    - type: image
      image: bg0
      fps: 30
      loops: 0
  # Move text in a rectangle
  slide_rollOverComplete:
    - type: text
      font_name: visitor
      bitmap_font: True
      text: "Wal\ntz"
      color: Red
      anchor_x: center
      anchor_y: middle
      x: 12
      y: 12
      animations:
        show_slide:
          - property: x, y
            value:  12, 20
            duration: 0.3s
          - property: x, y
            value:  20, 20
            duration: 0.3s
          - property: x, y
            value:  20, 12
            duration: 0.3s
          - property: x, y
            value:  12, 12
            duration: 0.3s
            repeat: True
    - type: text
      font_name: emulogic
      bitmap_font: True
      text: "3k"
      color: BBBBBB

slide_player:
  single_player_ball_started: 
    scoreSlide:
      priority: -1
  sg_rollovers_default_lit_complete: 
    slide_rollOverComplete:
      expire: 2s

sound_player:
  shot_adv_bonus_hit: elec_wood
  sg_rollovers_default_unlit_hit: blipPool
  sg_rollovers_default_lit_hit: elec_twip
  sg_rollovers_default_lit_complete: waltz
  shot_target_ml_low: elec_fuzz_tom
  sw_target: drumCymbalPool
  ball_drain: vinyl_backspin

show_player:
  sg_rollovers_default_lit_complete:
    blinkenShow:
      loops: 10
      show_tokens:
          lights: l_rollover_ll, l_rollover_ml, l_rollover_lr, l_rollover_mr
          color: FF0000


shots:
  #---------------------------
  # Rollovers
  #---------------------------
  shot_rollover_ml:
    switch: s_rollover_ml
    show_tokens:
      lights: l_rollover_ml
  shot_rollover_mr:
    switch: s_rollover_mr
    show_tokens:
      lights: l_rollover_mr
  shot_rollover_ll:
    switch: s_rollover_ll
    show_tokens:
      lights: l_rollover_ll
  shot_rollover_lr:
    switch: s_rollover_lr
    show_tokens:
      lights: l_rollover_lr

#---------------------------
# Targets
#---------------------------
  # The 3 targets in the middle ...
  # shot_target_ml_low:
  #   switch: s_target_ml_low
  #   show_tokens:
  #     lights: l_target_ml
  #   profile: grad
  shot_target_mm_low:
    switch: s_target_mm_low
    show_tokens:
      lights: l_target_mm
    profile: grad
  # shot_target_mr_low:
  #   switch: s_target_mr_low
  #   show_tokens:
  #     lights: l_target_mr
  #   profile: grad  

#---------------------------
# Shot groups / carousels
#---------------------------
# 4 rollover carousel
shot_groups:
  sg_rollovers:
    shots: shot_rollover_ll, shot_rollover_lr, shot_rollover_mr, shot_rollover_ml
    rotate_left_events:  s_flipper_left_1_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      sg_rollovers_default_lit_complete          