#config_version=5

mode:
  start_events: ball_starting
  priority: 50

#-----------------------------------------------------
# Basic variable_player (no special stuff, just simple hits)
# I use tags on the Switch devices to group the stuff
#-----------------------------------------------------
variable_player:
  # The 4 red rollover switches at the bottom
  sw_rollover:
    score: 50
  # Waltz bonus
  sg_rollovers_lit_complete:
    score: 3000

slides:
  scoreSlide:
    - type: text
      text: "(player1|score)"
      font_name: visitor
      color: black
      bitmap_font: True
      y: 15.0
      number_grouping: False
    - type: image
      image: bg0
      fps: 30
      loops: 0
  # Move text in a rectangle
  slide_rollOverComplete:
    - type: text
      font_name: visitor
      bitmap_font: True
      text: "Wal\ntz"
      color: Red
      anchor_x: center
      anchor_y: middle
      x: 12
      y: 12
      animations:
        show_slide:
          - property: x, y
            value:  12, 20
            duration: 0.3s
          - property: x, y
            value:  20, 20
            duration: 0.3s
          - property: x, y
            value:  20, 12
            duration: 0.3s
          - property: x, y
            value:  12, 12
            duration: 0.3s
            repeat: True
    - type: text
      font_name: emulogic
      bitmap_font: True
      text: "3k"
      color: BBBBBB

slide_player:
  single_player_ball_started:
    scoreSlide:
      priority: -1
  sg_rollovers_lit_complete:
    slide_rollOverComplete:
      expire: 2s

sound_player:
  # Background music start (stop is in sound.yaml)
  s_ball_on_plunger_inactive:
    orchestraTuneUp:
      action: stop
    music_pool:
      action: play
  # yellow targets
  shot_adv_bonus_hit: perc_till
  supermegahyperbonus: bass_trance_c
  # rollovers
  sg_rollovers_unlit_hit: blipPool
  sg_rollovers_lit_hit: elec_twip
  sg_rollovers_lit_complete: waltz
  ball_drain: vinyl_backspin

show_player:
  sg_rollovers_lit_complete:
    blinkenShow:
      loops: 10
      show_tokens:
          lights: l_rollover_ll, l_rollover_ml, l_rollover_lr, l_rollover_mr
          color: FF0000

shots:
  #---------------------------
  # Rollovers
  #---------------------------
  shot_rollover_ml:
    switch: s_rollover_ml
    show_tokens:
      lights: l_rollover_ml
  shot_rollover_mr:
    switch: s_rollover_mr
    show_tokens:
      lights: l_rollover_mr
  shot_rollover_ll:
    switch: s_rollover_ll
    show_tokens:
      lights: l_rollover_ll
  shot_rollover_lr:
    switch: s_rollover_lr
    show_tokens:
      lights: l_rollover_lr

#---------------------------
# Shot groups / carousels
#---------------------------
# 4 rollover carousel
shot_groups:
  sg_rollovers:
    shots: shot_rollover_ll, shot_rollover_lr, shot_rollover_mr, shot_rollover_ml
    rotate_left_events:  s_flipper_left_1_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      sg_rollovers_lit_complete
