#config_version=5

mode:
  start_events: ball_starting
  priority: 100

#-----------------------------------------------------
# Basic scoring (no special stuff, just simple hits)
# I use tags on the Switch devices to group the stuff
#-----------------------------------------------------
scoring:
  # All yellow targets (strong shots)
  # sw_target:
  #   score: 5
  # CAPTIVE Holes
  sw_captive:
    score: 5
  # The 4 red rollover switches at the bottom
  sw_rollover:
    score: 50
  sg_rollovers_default_lit_complete:
    score: 500
  # Hit center target to light up "Ball returns" 
  # in left bottom outlane, to kick ball back onto
  # playfield and score 3000 points
  s_outlane_l_active{current_player.shot_target_mm_low_default==1}:
    score: 3000

slides:
  scoreSlide:
    - type: text
      text: "(player1|score)"
      font_name: visitor
      color: black
      bitmap_font: True
      y: 15.0
      number_grouping: False
    - type: image
      image: bg0
      fps: 30
      loops: 0
  # Move text in a rectangle
  slide_rollOverComplete:
    - type: text
      font_name: visitor
      bitmap_font: True
      text: "Wal\ntz"
      color: Red
      anchor_x: center
      anchor_y: middle
      x: 12
      y: 12
      animations:
        show_slide:
          - property: x, y
            value:  12, 20
            duration: 0.3s
          - property: x, y
            value:  20, 20
            duration: 0.3s
          - property: x, y
            value:  20, 12
            duration: 0.3s
          - property: x, y
            value:  12, 12
            duration: 0.3s
            repeat: True
    - type: text
      font_name: emulogic
      bitmap_font: True
      text: "500"
      color: 999999

slide_player:
  single_player_ball_started: 
    scoreSlide:
      priority: -1
  sg_rollovers_default_lit_complete: 
    slide_rollOverComplete:
      expire: 2s

sound_player:
  shot_adv_bonus_hit: elec_wood
  sg_rollovers_default_unlit_hit: blipPool
  sg_rollovers_default_lit_hit: elec_twip
  sg_rollovers_default_lit_complete: waltz
  shot_target_ml_low: elec_fuzz_tom
  sw_target: drumCymbalPool
  ball_drain: vinyl_backspin

show_player:
  sg_rollovers_default_lit_complete:
    blinkenShow:
      loops: 10
      show_tokens:
          lights: l_rollover_ll, l_rollover_ml, l_rollover_lr, l_rollover_mr
          color: FF0000