#config_version=5
config:
- hardware.yaml
- shots.yaml
- sound.yaml
- keyboard.yaml

modes:
  - base
  # Increase jet-bumper value with top 2 targets
  - jet_bumper
  - jet_bumper_strong
  # Track bonus points with LED row
  - bonus10
  # End of ball bonus, automatically configured to start when the ball ends
  - bonus
  # ball hold, spin the well and give out random rewards
  - roulette
  # left and right outlanes and savers
  - outlanes
  - high_score

game:
  balls_per_game: 3
  max_players: 4

hardware:
  platform: fantastic_platform
  rgb_dmd: rpi_dmd

fantastic:
  debug: True
  port: /dev/ttyACM0
  led_clock_0: 3200000  #WS2812 High speed mode
  led_clock_1: 2400000  #WS2811 Low speed mode
  led_clock_2: 3200000  #WS2812 High speed mode

rpi_dmd:
  cols: 32
  rows: 32
  gpio_slowdown: 2
  pwm_lsb_nanoseconds: 300
  drop_privileges: 1

#-------------------
# Player variables
#-------------------
player_vars:
  # Hom much do different tragets score at the beginning
  jetBumperWorth:
    initial_value: 10
  # Will change to 2000 when ultraBonus is achieved
  bonus10Worth:
    initial_value: 1000

#-------------------
# ** Only 1 (so far) **
#-------------------
playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

#-------------------
# ** Autofire coils **
#-------------------
autofire_coils:
  # jet bumpers
  af_jet_bump_low:
    coil:   c_jet_bump_low
    switch: s_jet_bump_low
  af_jet_bump_tl:
    coil:   c_jet_bump_tl
    switch: s_jet_bump_tl
  af_jet_bump_tr:
    coil:   c_jet_bump_tr
    switch: s_jet_bump_tr
  af_jet_bump_t:
    coil:   c_jet_bump_t
    switch: s_jet_bump_t
  # Left outlane kickback saver
  af_outlane_l_kickback:
    coil:   c_outlane_l_kickback
    switch: s_outlane_l
    enable_events: player_shot_left_kickback{value==1}
    disable_events: ball_ending, service_mode_entered, player_shot_left_kickback{value==0}
  # Right outlane gate saver
  # (only enabled by roulette)
  af_outlane_r_gate:
    coil:   c_outlane_r_gate
    switch: s_outlane_r
    enable_events: player_shot_right_gate{value==1}
    disable_events: ball_ending, service_mode_entered, player_shot_right_gate{value==0}

#-------------------
# ** Ball Devices **
#-------------------
ball_devices:
  bd_trough:
    ball_switches: s_trough
    entrance_count_delay: 300ms
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain
    debug: True
  bd_plunger:
    ball_switches: s_ball_on_plunger
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    mechanical_eject: True
  # SPIN ball holds
  bd_captive_l:
    ball_switches: s_captive_l
    eject_coil: c_captive_l
    entrance_count_delay: 100ms
    eject_timeouts: 1s
  bd_captive_t:
    ball_switches: s_captive_t
    eject_coil: c_captive_t
    entrance_count_delay: 100ms
    eject_timeouts: 1s
  bd_captive_r:
    ball_switches: s_captive_r
    eject_coil: c_captive_r
    entrance_count_delay: 100ms
    eject_timeouts: 1s

ball_holds:
  bh_captive_l:
    hold_devices: bd_captive_l
    release_one_events: mode_roulette_stopped
  bh_captive_t:
    hold_devices: bd_captive_t
    release_one_events: mode_roulette_stopped
  bh_captive_r:
    hold_devices: bd_captive_r
    release_one_events: mode_roulette_stopped

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left_1
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right

#-------------------------------------------------------
# Back glass stuff
#-------------------------------------------------------
score_reels:
  score_p1_4:
    coil_inc: c_score_p1_4
    switch_0: s_score_p1_4
    repeat_pulse_time: 100
  score_p1_3:
    coil_inc: c_score_p1_3
    switch_0: s_score_p1_3
    repeat_pulse_time: 100
  score_p1_2:
    coil_inc: c_score_p1_2
    switch_0: s_score_p1_2
    repeat_pulse_time: 100
  score_p1_1:
    coil_inc: c_score_p1_1
    switch_0: s_score_p1_1
    repeat_pulse_time: 100
  score_p3_4:
    coil_inc: c_score_p3_4
    switch_0: s_score_p3_4
    repeat_pulse_time: 100
  score_p3_3:
    coil_inc: c_score_p3_3
    switch_0: s_score_p3_3
    repeat_pulse_time: 100
  score_p3_2:
    coil_inc: c_score_p3_2
    switch_0: s_score_p3_2
    repeat_pulse_time: 100
  score_p3_1:
    coil_inc: c_score_p3_1
    switch_0: s_score_p3_1
    repeat_pulse_time: 100

score_reel_groups:
  player1:
    reels: score_p1_4, score_p1_3, score_p1_2, score_p1_1, None
    tags: player1
    lights_tag: l_bg_p1_score
  player3:
    reels: score_p3_4, score_p3_3, score_p3_2, score_p3_1, None
    tags: player3
    lights_tag: l_bg_p3_score

info_lights:
    match_00:
        light: l_bg_00
    match_10:
        light: l_bg_10
    match_20:
        light: l_bg_20
    match_30:
        light: l_bg_30
    match_40:
        light: l_bg_40
    match_50:
        light: l_bg_50
    match_60:
        light: l_bg_60
    match_70:
        light: l_bg_70
    match_80:
        light: l_bg_80
    match_90:
        light: l_bg_90
    ball_1:
        light: l_bg_ball_1
    ball_2:
        light: l_bg_ball_2
    ball_3:
        light: l_bg_ball_3
    ball_4:
        light: l_bg_ball_4
    ball_5:
        light: l_bg_ball_5
    player_1:
        light: l_bg_nplayer_1
    player_2:
        light: l_bg_nplayer_2
    player_3:
        light: l_bg_nplayer_3
    player_4:
        light: l_bg_nplayer_4
    tilt:
        light: l_bg_tilt
    game_over:
        light: l_bg_gameover
    player_up_1:
        light: l_bg_p1_score
    player_up_2:
        light: l_bg_p2_score
    player_up_3:
        light: l_bg_p3_score
    player_up_4:
        light: l_bg_p4_score

show_player:
  init_done:
    cello_guy:
      loops: -1
    flute_guy:
      loops: -1


#-------------------------------------------------------
# Multimedia stuff
#-------------------------------------------------------
window:
  width: 256
  height: 256
  title: Fan-Tas-Tic Pinball
  resizable: True
  fullscreen: False
  borderless: False
  exit_on_escape: True
  source_display: wnddmd

displays:
  wnddmd:
    width:  32
    height: 32
    default: True

rgb_dmds:
  my_dmd:
     brightness: 1.0
     gamma: 1.0
     platform: rpi_dmd
     source_display: wnddmd
     fps: 30
     only_send_changes: True

image_pools:
  bgAni_pool:
    images:
      - bg0
      - bg1
      - bg2
      - bg3
      - bg4
    type: random
    load: preload

# show_player:
#   game_will_end:
#     end_of_game_show

#------------------------------------
# Styles don't seem to work yet :(
#------------------------------------
# widget_styles:
#   text_default:
#     font_name: dmd_small
#     bitmap_font: True
# text_emulogic:
#   font_name: emulogic
#   bitmap_font: True
# text_minecraftia:
#   font_name: minecraftia
#   bitmap_font: True
# text_visitor:
#   font_name: visitor
#   bitmap_font: True
