#config_version=5
config:
- hardware.yaml
- shots.yaml
- sound.yaml
- back_glass.yaml
- keyboard.yaml

modes:
  - base
  # Increase jet-bumper value with top 2 targets
  - jet_bumper
  # Track bonus points with LED row
  - bonus10
  # End of ball bonus, automatically configured to start when the ball ends
  - bonus
  # ball hold, spin the well and give out random rewards
  - roulette
  # left and right outlanes and savers
  - outlanes
  - stars
  - high_score
  - credits
  - tilt

hardware:
  platform: fantastic_platform
  rgb_dmd: rpi_dmd

game:
  balls_per_game: 3
  max_players: 4

credits:
    max_credits: 12
    free_play: True
    switches:
        - switch: s_coin
          type: money
          value: .25
    pricing_tiers:
        - price: .25
          credits: 1
    fractional_credit_expiration_time: 15m
    credit_expiration_time: 2h
    persist_credits_while_off_time: 1h
    free_play_string: FREE
    credits_string: CRED

logging:
    console:
         platforms: full

# Comment this block if you're simulating on the host
fantastic:
  debug: True
  port: /dev/ttyACM0
  led_clock_0: 3200000  #WS2812 High speed mode
  led_clock_1: 2400000  #WS2811 Low speed mode
  led_clock_2: 3200000  #WS2812 High speed mode

rpi_dmd:
  cols: 32
  rows: 32
  gpio_slowdown: 2
  pwm_lsb_nanoseconds: 300
  drop_privileges: False

#-------------------
# Player variables
#-------------------
player_vars:
  # Hom much do different tragets score at the beginning
  jetBumperWorth:
    initial_value: 10
  # Will change to 2000 when ultraBonus is achieved
  bonus10Worth:
    initial_value: 1000
  # Label on roulette slide
  roulette_text:
    initial_value: ''
    value_type: str

#-------------------
# ** Only 1 (so far) **
#-------------------
playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

#-------------------
# ** Autofire coils **
#-------------------
autofire_coils:
  # jet bumpers
  af_jet_bump_low:
    coil:   c_jet_bump_low
    switch: s_jet_bump_low
  af_jet_bump_tl:
    coil:   c_jet_bump_tl
    switch: s_jet_bump_tl
  af_jet_bump_tr:
    coil:   c_jet_bump_tr
    switch: s_jet_bump_tr
  af_jet_bump_t:
    coil:   c_jet_bump_t
    switch: s_jet_bump_t
  # Left outlane kickback saver
  af_outlane_l_kickback:
    coil:   c_outlane_l_kickback
    switch: s_outlane_l
    enable_events: player_shot_left_kickback{value==1}
    disable_events: ball_ending, service_mode_entered, player_shot_left_kickback{value==0}
  # Right outlane gate saver
  # (only enabled by roulette)
  af_outlane_r_gate:
    coil:   c_outlane_r_gate
    switch: s_outlane_r
    enable_events: player_shot_right_gate{value==1}
    disable_events: ball_ending, service_mode_entered, player_shot_right_gate{value==0}

#-------------------
# ** Ball Devices **
#-------------------
ball_devices:
  bd_trough:
    ball_switches: s_trough
    entrance_count_delay: 300ms
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain
  bd_plunger:
    ball_switches: s_ball_on_plunger
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    mechanical_eject: True
  # SPIN ball holds
  bd_captive_l:
    ball_switches: s_captive_l
    eject_coil: c_captive_l
    entrance_count_delay: 100ms
    eject_timeouts: 1s
  bd_captive_t:
    ball_switches: s_captive_t
    eject_coil: c_captive_t
    entrance_count_delay: 100ms
    eject_timeouts: 1s
  bd_captive_r:
    ball_switches: s_captive_r
    eject_coil: c_captive_r
    entrance_count_delay: 100ms
    eject_timeouts: 1s

ball_holds:
  bh_captive_l:
    hold_devices: bd_captive_l
    release_one_events: mode_roulette_stopped
  bh_captive_t:
    hold_devices: bd_captive_t
    release_one_events: mode_roulette_stopped
  bh_captive_r:
    hold_devices: bd_captive_r
    release_one_events: mode_roulette_stopped

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left_1
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right

#-------------------------------------------------------
# Multimedia stuff
#-------------------------------------------------------
window:
  width: 256
  height: 256
  title: Fan-Tas-Tic Pinball
  resizable: True
  fullscreen: False
  borderless: False
  exit_on_escape: True
  source_display: wnddmd

displays:
  wnddmd:
    width:  32
    height: 32
    round_anchor_x: left
    round_anchor_y: top
    default: True

rgb_dmds:
  my_dmd:
     brightness: 1.0
     gamma: 1.0
     platform: rpi_dmd
     source_display: wnddmd
     fps: 30
     only_send_changes: True

# play a random background animation
# big thanks to the pixelmatrix community !!
# https://community.pixelmatix.com/c/animated-gifs/9
image_pools:
  bgAni_pool:
    images:
      - 5OejiSj
      # - bg11
      - bg22
      - bg2
      - bg3
      - bg5
      - bg8
      - bg0
      - bg18
      - bg21
      - bg25
      - bg33
      - bg4
      - bg7
    type: random
    load: preload

# show_player:
#   game_will_end:
#     end_of_game_show

widget_styles:
  text_default:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_bottom: 3
    adjust_top: 2
  visitor:
    font_name: visitor1
    font_size: 10
