#config_version=5

#------------------------------------------------------------------------
# Default shots (when no special mode overrides this)
#------------------------------------------------------------------------
shot_profiles:
    # Off + 9 different colors
    rainbow:
      show: fast_rainbow
      states:
        - name: 0
          start_step: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
        - name: 5
        - name: 6
        - name: 7
        - name: 8
        - name: 9
    # Off, 4 x increasing brightness, unlimited flashing
    grad:
      show: grad
      states:
        - name: 0
          start_step: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
          show: blinkenShowWhite
    stars:
      show: stars
      states:
        - name: 0
          start_step: 0
        - name: 1
        - name: 2
        - name: 3
shows:
  stars:
    - lights:
        l_star1: off
        l_star2: off
        l_star3: off
    - lights:
        l_star1: FFFFFF
        l_star2: off
        l_star3: off
    - lights:
        l_star1: FFFFFF
        l_star2: FFFFFF
        l_star3: off
    - lights:
        l_star1: FFFFFF
        l_star2: FFFFFF
        l_star3: FFFFFF

  rainbow:
    - lights:
        (lights): off
    - lights:
        (lights): white-f1s
    - lights:
        (lights): green-f1s
    - lights:
        (lights): red-f1s
    - lights:
        (lights): yellow-f1s
    - lights:
        (lights): blue-f1s
    - lights:
        (lights): orange-f1s
    - lights:
        (lights): magenta-f1s
    - lights:
        (lights): cyan-f1s
    - lights:
        (lights): purple-f1s

  fast_rainbow:
    - lights:
        (lights): off
    - lights:
        (lights): white
    - lights:
        (lights): green
    - lights:
        (lights): red
    - lights:
        (lights): yellow
    - lights:
        (lights): blue
    - lights:
        (lights): orange
    - lights:
        (lights): magenta
    - lights:
        (lights): cyan
    - lights:
        (lights): purple

  grad:
    - lights:
        (lights): 000000
    - lights:
        (lights): 111111
    - lights:
        (lights): 888888
    - lights:
        (lights): FFFFFF

  blinkenShowWhite:
    - time: 0
      lights:
        (lights): FFFFFF
    - time: +0.1s
      lights:
        (lights): 000000
    - time: +0.1s

  blinkenShow:
    - time: 0
      lights:
        (lights): (color)
    - time: +0.1s
      lights:
        (lights): 000000
    - time: +0.1s
