#config_version=5

#------------------------------------------------------------------------
# Default shots (when no special mode overrides this)
#------------------------------------------------------------------------
shot_profiles:
    rainbow:
      # loop: True
      show: rainbow
      states:
        - name: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
        - name: 5
        - name: 6
        - name: 7
        - name: 8
        - name: 9
    flash:
      states:
        - name: off
        - name: hit
          show: flash
    grad:
      show: grad
      states:
        - name: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
          show: flash
shows:
    rainbow:
      - lights:
          (lights): off
      - lights:
          (lights): white
      - lights:
          (lights): yellow
      - lights:
          (lights): red
      - lights:
          (lights): green
      - lights:
          (lights): blue
      - lights:
          (lights): purple
      - lights:
          (lights): magenta
      - lights:
          (lights): cyan
      - lights:
          (lights): orange

    grad:
      - lights:
          (lights): 000000
      - lights:
          (lights): 111111
      - lights:
          (lights): 888888
      - lights:
          (lights): FFFFFF
    rolloverShow:
      - time: 0
        lights:
          l_rollover_lr: FFFFFF
          l_rollover_ll: FFFFFF
          l_rollover_mr: FFFFFF
          l_rollover_ml: FFFFFF
      - time: +0.1s
        lights:
          l_rollover_lr: 000000
          l_rollover_ll: 000000
          l_rollover_mr: 000000
          l_rollover_ml: 000000
      - time: +0.1s
    blinkenShow:
      - time: 0
        lights:
          (lights): FFFFFF
      - time: +0.1s
        lights:
          (lights): 000000
      - time: +0.1s      

shots:
  #---------------------------
  # Rollovers
  #---------------------------
  shot_rollover_tl:
    switch: s_rollover_tl
    show_tokens:
      lights: l_rollover_tl
  shot_rollover_tr:
    switch: s_rollover_tr
    show_tokens:
      lights: l_rollover_tr
  shot_rollover_ml:
    switch: s_rollover_ml
    show_tokens:
      lights: l_rollover_ml
  shot_rollover_mr:
    switch: s_rollover_mr
    show_tokens:
      lights: l_rollover_mr
  shot_rollover_ll:
    switch: s_rollover_ll
    show_tokens:
      lights: l_rollover_ll
  shot_rollover_lr:
    switch: s_rollover_lr
    show_tokens:
      lights: l_rollover_lr

#---------------------------
# Lower jet-Bunmper
#---------------------------
  shot_jb_low:
    switch: s_jet_bump_low
    show_tokens:
      lights: l_jet_bump_low
    profile: rainbow

#---------------------------
# Targets
#---------------------------
  # The 3 targets in the middle ...
  shot_target_ml_low:
    switch: s_target_ml_low
    show_tokens:
      lights: l_target_ml
    profile: grad
  shot_target_mm_low:
    switch: s_target_mm_low
    show_tokens:
      lights: l_target_mm
    profile: rainbow
  shot_target_mr_low:
    switch: s_target_mr_low
    show_tokens:
      lights: l_target_mr
    profile: grad  