#config_version=5

#------------------------------------------------------------------------
# Default shots (when no special mode overrides this)
#------------------------------------------------------------------------
shot_profiles:
    # Off + 9 different colors
    rainbow:
      show: rainbow
      states:
        - name: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
        - name: 5
        - name: 6
        - name: 7
        - name: 8
        - name: 9
    # Off, 4 x increasing brightness, unlimited flashing
    grad:
      show: grad
      states:
        - name: 0
        - name: 1
        - name: 2
        - name: 3
        - name: 4
          show: blinkenShow
          show_tokens:
            color: FFFFFF
shows:
    rainbow:
      - lights:
          (lights): off
      - lights:
          (lights): white-f1s
      - lights:
          (lights): yellow-f1s
      - lights:
          (lights): red-f1s
      - lights:
          (lights): green-f1s
      - lights:
          (lights): blue-f1s
      - lights:
          (lights): orange-f1s
      - lights:
          (lights): magenta-f1s
      - lights:
          (lights): cyan-f1s
      - lights:
          (lights): purple-f1s

    grad:
      - lights:
          (lights): 000000
      - lights:
          (lights): 111111
      - lights:
          (lights): 888888
      - lights:
          (lights): FFFFFF      

    blinkenShow:
      - time: 0
        lights:
          (lights): (color)
      - time: +0.1s
        lights:
          (lights): 000000
      - time: +0.1s      

shots:
  #---------------------------
  # Rollovers
  #---------------------------
  shot_rollover_ml:
    switch: s_rollover_ml
    show_tokens:
      lights: l_rollover_ml
  shot_rollover_mr:
    switch: s_rollover_mr
    show_tokens:
      lights: l_rollover_mr
  shot_rollover_ll:
    switch: s_rollover_ll
    show_tokens:
      lights: l_rollover_ll
  shot_rollover_lr:
    switch: s_rollover_lr
    show_tokens:
      lights: l_rollover_lr

#---------------------------
# Targets
#---------------------------
  # The 3 targets in the middle ...
  shot_target_ml_low:
    switch: s_target_ml_low
    show_tokens:
      lights: l_target_ml
    profile: grad
  shot_target_mm_low:
    switch: s_target_mm_low
    show_tokens:
      lights: l_target_mm
    profile: rainbow
  shot_target_mr_low:
    switch: s_target_mr_low
    show_tokens:
      lights: l_target_mr
    profile: grad  

#---------------------------
# Shot groups / carousels
#---------------------------
# 4 rollover carousel
shot_groups:
  sg_rollovers:
    shots: shot_rollover_ll, shot_rollover_lr, shot_rollover_mr, shot_rollover_ml
    rotate_left_events:  s_flipper_left_1_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      sg_rollovers_default_lit_complete