#config_version=5
#-------------------------------
# Everything Jet-bumper related
#-------------------------------
# Includes the multiplier, the 2 top targets and the rubbers

mode:
  start_events: ball_starting
  priority: 100

scoring:
  # The 3 top jet-bumpers have a multiplier
  sg_jetbumptargets_complete:
    jetBumperWorth: 20
  sw_jetBumper:
    score: current_player.jetBumperWorth
  # RUBBER bands on top part
  sw_rubber:
    score: 10

#---------------------------
# Target shots
#---------------------------
shots:
  # Top 2 targets are a carousel and just light when hit
  shot_target_tr:
    switch: s_target_on_bump_tr
    show_tokens:
      lights: l_targ_ur
  shot_target_tl:
    switch: s_target_on_bump_tl
    show_tokens:
      lights: l_targ_ul
  # if both are hit, increase jet bumper multiplier value (score_player)
  # and change their color (shot_profile below)
  shot_increaseBumper:
    advance_events: sg_jetbumptargets_complete
    show_tokens:
      lights: l_jet_bump_t, l_jet_bump_tl, l_jet_bump_tr
    profile: rainbow

#---------------------------
# Shot groups / carousels
#---------------------------
shot_groups:
  # 2 target at top carousel
  sg_jetBumpTargets:
    shots: shot_target_tl, shot_target_tr
    rotate_left_events:  s_flipper_left_1_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      sg_jetbumptargets_complete

slides:
  slide_jetBumpMultiplier:
    - type: text
      text: "BUMP\n(player1|jetBumperWorth)"
      font_name: visitor
      color: 88FF88
      bitmap_font: True

slide_player:
  sg_jetbumptargets_complete:
    slide_jetBumpMultiplier:
      expire: 1.0s

sound_player:
  sw_jetBumper: drumTomPool
  sw_rubber: bdPool

show_player:
  # Make upper targets flash on complete
  sg_jetbumptargets_complete:
    blinkenShow:
      loops: 5
      show_tokens:
        lights: l_targ_ul, l_targ_ur
        color: 00FF00
  # Make lower jet-bumper glow on hit
  s_jet_bump_low_active:
    jet_glow:
      loops: 0
      show_tokens: 
        lights: l_jet_bump_low

