#config_version=5
#-------------------------------
# Everything Jet-bumper related
#-------------------------------
# * Lower jet bumper always lit and scores 100
# * Top left or right target will lite the other 3
#   bumpers to score N*100 instead of 10 points

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  # The 3 top jet-bumpers have a multiplier
  sg_jetbumptargets_lit_complete:
    jetBumperWorth: 100
  sw_jetBumper:
    score: current_player.jetBumperWorth
  s_jet_bump_low_active:
    score: 100
  # RUBBER bands on top part
  sw_rubber:
    score: 10

#---------------------------
# Target shots
#---------------------------
shots:
  # Top 2 targets are a carousel and just light when hit
  shot_target_tr:
    switch: s_target_on_bump_tr
    show_tokens:
      lights: l_targ_ur
  shot_target_tl:
    switch: s_target_on_bump_tl
    show_tokens:
      lights: l_targ_ul
  # if both are hit, increase jet bumper multiplier value (score_player)
  # and change their color (shot_profile below)
  shot_increaseBumper:
    advance_events: sg_jetbumptargets_lit_complete
    show_tokens:
      lights: l_jet_bump_t, l_jet_bump_tl, l_jet_bump_tr
    profile: rainbow

#---------------------------
# Shot groups / carousels
#---------------------------
shot_groups:
  # 2 target at top carousel
  sg_jetbumptargets:
    shots: shot_target_tl, shot_target_tr
    rotate_left_events:  s_flipper_left_1_active
    rotate_right_events: s_flipper_right_active
    reset_events: sg_jetbumptargets_lit_complete

slides:
  slide_jetBumpMultiplier:
    - type: text
      text: "BUMP\n(player1|jetBumperWorth)"
      color: 88FF88
      style: visitor

slide_player:
  sg_jetbumptargets_lit_complete:
    slide_jetBumpMultiplier:
      expire: 1.0s

sound_player:
  s_jet_bump_low_active: snPool
  sw_rubber: bdPool
  # yellow targets on top
  sg_jetbumptargets_hit: bass_hit_c
  sg_jetbumptargets_lit_complete: bass_hard_c

show_player:
  # Make upper targets flash on complete
  sg_jetbumptargets_lit_complete:
    blinkenShow:
      loops: 5
      show_tokens:
        lights: l_targ_ul, l_targ_ur
        color: 00FF00

  # Make jet-bumpers glow on hit
  s_jet_bump_tr_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_jet_bump_tr
  s_jet_bump_t_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_jet_bump_t
  s_jet_bump_tl_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_jet_bump_tl
  s_jet_bump_low_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_jet_bump_low

  # Make other stuff glow on hit
  s_rubber_tl_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_targ_ul
  s_rubber_tr_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_side_ur
  s_rubber_targ_l_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_target_ml, l_target_mm
  s_rubber_targ_r_active:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_target_mr, l_target_mm

shows:
  jet_glow:
    - time: 0
      lights:
        (lights): FFFFFF
    - time: +0.1s
      lights:
        (lights): 000000-f1s
    - time: +1s
