#config_version=5
#-------------------------------
# Everything Outlane related
#-------------------------------
# * Middle yellow target / roulette spin enables outlnane saver
# * on the left is kickbakc on the right gate
# this relies on the autofire-coils in config/config.yaml
# Also takes care of
#   * AB lanes
#   * 3 star extraball

mode:
  start_events: ball_starting
  priority: 100

shots:
  #---------------------------
  # Middle Target activates left outlane saver
  #---------------------------
  left_kickback:
    switch: s_target_mm_low
    reset_events:
      ball_ending: 0
      s_outlane_l_active{current_player.shot_left_kickback==1}: 3s
    # Use default (off/on) shot profile to light `Ball returns` LED
    show_tokens:
      lights: l_outlane_l

  right_gate:
    hit_events: roulette_open_gate
    reset_events:
      ball_ending: 0
      s_outlane_r_active{current_player.shot_right_gate==1}: 3s
    # Use default (off/on) shot profile to light `Ball returns` LED
    show_tokens:
      lights: l_outlane_r

  ab_lanes:
    hit_events: roulette_ab_lanes
    reset_events: ball_ending
    show_tokens:
      lights: l_A_lane, l_B_lane

  bonus_stars:
    hit_events: roulette_star
    # reset_events: ball_ending
    profile: stars

show_player:
  s_target_mm_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_mm
        color: FFFFFF

  # Blink outlane light before switching it off, when a ball was saved
  s_outlane_l_active{current_player.shot_left_kickback==1}:
    blinkenShow:
      loops: 15
      show_tokens:
        lights: l_outlane_l
        color: FFFFFF

  s_outlane_r_active{current_player.shot_right_gate==1}:
    blinkenShow:
      loops: 15
      show_tokens:
        lights: l_outlane_r
        color: FFFFFF

variable_player:
  # Hit center target to light up "Ball returns"
  # in left bottom outlane, to kick ball back onto
  # playfield and score 3000 points
  s_outlane_l_active{current_player.shot_left_kickback==1}:
    score: 3000
  # Gate save scores 3000
  s_outlane_r_active{current_player.shot_right_gate==1}:
    score: 3000
  # When AB lanes light are ON, they score 3000
  s_lane_tl_active{current_player.shot_ab_lanes==1}:
    score: 3000
  s_lane_tr_active{current_player.shot_ab_lanes==1}:
    score: 3000

extra_balls:
  eb_stars:
    award_events: player_shot_bonus_stars{value==3}
