#config_version=5
#-------------------------------
# Everything Outlane related
#-------------------------------
# * Middle yellow target / roulette spin enables outlnane saver
# * on the left is kickbakc on the right gate
# this relies on the autofire-coils in config/config.yaml
# Also takes care of
#   * AB lanes

mode:
  start_events: ball_starting
  priority: 200

shots:
  #---------------------------
  # Middle Target activates left outlane saver
  #---------------------------
  left_kickback:
    switch: s_target_mm_low
    reset_events:
      ball_ending: 0
      s_outlane_l_active{current_player.shot_left_kickback==1}: 3s
    # Use default (off/on) shot profile to light `Ball returns` LED
    show_tokens:
      lights: l_outlane_l
  right_gate:
    hit_events: roulette_open_gate
    reset_events:
      ball_ending: 0
      s_outlane_r_active{current_player.shot_right_gate==1}: 3s
    # Use default (off/on) shot profile to light `Ball returns` LED
    show_tokens:
      lights: l_outlane_r
  ab_lanes:
    hit_events: roulette_ab_lanes
    reset_events: ball_ending
    show_tokens:
      lights: l_A_lane, l_B_lane

show_player:
  s_target_mm_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_mm
        color: FFFFFF
  # Blink outlane light before switching it off, when a ball was saved
  s_outlane_l_active{current_player.shot_left_kickback==1}:
    blinkenShow:
      loops: 15
      show_tokens:
        lights: l_outlane_l
        color: FFFFFF
  s_outlane_r_active{current_player.shot_right_gate==1}:
    blinkenShow:
      loops: 15
      show_tokens:
        lights: l_outlane_r
        color: FFFFFF
  a_lane_scored:
    blinkenShowWhite:
      loops: 3
      show_tokens:
        lights: l_A_lane
  b_lane_scored:
    blinkenShowWhite:
      loops: 3
      show_tokens:
        lights: l_B_lane

event_player:
  s_lane_tl_active{current_player.shot_ab_lanes==1}:
    a_lane_scored
  s_lane_tr_active{current_player.shot_ab_lanes==1}:
    b_lane_scored

variable_player:
  # Hit center target to light up "Ball returns"
  # in left bottom outlane, to kick ball back onto
  # playfield and score 3000 points
  s_outlane_l_active{current_player.shot_left_kickback==1}:
    score: 3000
  # Gate save scores 3000
  s_outlane_r_active{current_player.shot_right_gate==1}:
    score: 3000
  # When AB lanes light are ON, they score 3000
  a_lane_scored:
    score: 3000
  b_lane_scored:
    score: 3000

sound_player:
  a_lane_scored:
    bass_drop_c
  b_lane_scored:
    bass_drop_c
