#config_version=5
#-------------------------------
# Controls the 10 playfield Bonus lights
#-------------------------------
mode:
  start_events: ball_starting
  priority: 101
  code: bonus10.Bonus10

show_player:
  # Make adv bonus targets flash on hit
  s_rollover_tl_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tl
        color: FF0000
  s_rollover_tr_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tr
        color: FF0000
  s_target_ml_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_ml
        color: FFFFFF
  s_target_mr_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_mr
        color: FFFFFF