#config_version=5
#-------------------------------
# Controls the 10 playfield Bonus lights
#-------------------------------
# bonus is advanced by top 2 rollovers or middle 2 targets
mode:
  start_events: ball_starting
  code: bonus10.Bonus10
  priority: 200

variable_player:
  shot_adv_bonus_hit:
    score: current_player.shot_adv_bonus_bonus10_profile * 200

shots:
  shot_adv_bonus:
    switch: s_rollover_tl, s_rollover_tr, s_target_ml_low, s_target_mr_low

slides:
  ultra_bonus10_slide:
    - type: text
      text: "(player1|bonus10HitCount)x"
      style: big
      color: yellow
    - type: text
      text: "(player1|bonus10Worth)"
      color: white
      y: 7
    - type: text
      text: "ULTRA bonus"
      color: white
      y: 25
      x: 35
      animations:
        add_to_slide:
          - property: x
            value: -25
            duration: 3s
          - property: x
            value: 32
            duration: 0 s
    - type: image
      image: bg20
      fps: 30
      loops: -1

slide_player:
  superMegaHyperBonus:
    ultra_bonus10_slide:
      expire: 3s

show_player:
  # Make adv bonus targets flash on hit
  s_rollover_tl_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tl
        color: FF0000
  s_rollover_tr_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tr
        color: FF0000
  s_target_ml_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_ml
        color: FFFFFF
  s_target_mr_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_mr
        color: FFFFFF
  strong_hit:
    jet_glow:
      loops: 0
      show_tokens:
        lights: l_target_ml, l_target_mm, l_target_mr

# Strong target hits make the middle lights glow
event_player:
  s_target_ml_high_active:
    strong_hit
  s_target_mm_high_active:
    strong_hit
  s_target_mr_high_active:
    strong_hit

sound_player:
  strong_hit:
    perc_snap2
