#config_version=5
#-------------------------------
# Controls the 10 playfield Bonus lights
#-------------------------------
# bonus is advanced by top 2 rollovers or middle 2 targets
mode:
  start_events: ball_starting
  priority: 101
  code: bonus10.Bonus10

scoring:
  shot_adv_bonus_hit: 
    score: current_player.shot_adv_bonus_bonus10_profile * 200

shots:
  shot_adv_bonus:
    switch: s_rollover_tl, s_rollover_tr, s_target_ml_low, s_target_mr_low

slides:
  ultra_bonus10_slide:
    - type: text
      text: "\n(player1|bonus10HitCount)\nx(player1|bonus10Worth)"
      font_name: CG-pixel
      color: white
      bitmap_font: True
    - type: text
      text: "ULTRA bonus"
      font_name: CG-pixel
      color: white
      y: 23
      x: 35
      bitmap_font: True
      animations:
        add_to_slide:
          - property: x
            value: -25
            duration: 3s
          - property: x
            value: 32
            duration: 0 s      
    - type: image
      image: bg20
      fps: 30
      loops: 0

slide_player:
  superMegaHyperBonus:
    ultra_bonus10_slide:
      expire: 3s

show_player:
  # Make adv bonus targets flash on hit
  s_rollover_tl_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tl
        color: FF0000
  s_rollover_tr_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_rollover_tr
        color: FF0000
  s_target_ml_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_ml
        color: FFFFFF
  s_target_mr_low_active:
    blinkenShow:
      loops: 2
      show_tokens:
        lights: l_target_mr
        color: FFFFFF